{$op_names = [
	'BONUS'=>$_TRANS['Bonus'],
	'PENALTY'=>$_TRANS['Penalty'],
	'CASHIN'=>$_TRANS['Add funds'],
	'CASHOUT'=>$_TRANS['Withdraw'],
	'EX'=>$_TRANS['Exchange'],
	'TR'=>$_TRANS['Transfer'],
	'TRIN'=>$_TRANS['Transfer in'],
	'BUY'=>$_TRANS['Buy'],
	'SELL'=>$_TRANS['Sell'],
	'BUY2'=>$_TRANS['Buy'],
	'SELL2'=>$_TRANS['Sell'],
	'REF'=>$_TRANS['Referral'],
	'GIVE'=>$_TRANS['Deposit'],
	'TAKE'=>$_TRANS['Removal'],
	'CALCIN'=>$_TRANS['Profit'],
	'CALCOUT'=>$_TRANS['Deduction']
] scope='global'}
{$op_statuses = [
	0=>$_TRANS['Prepeared'],
	1=>$_TRANS['Waiting confirmation'],
	2=>$_TRANS['Pending'],
	3=>$_TRANS['Complete'],
	4=>$_TRANS['Rejected'],
	5=>$_TRANS['Canceled']
] scope='global'}
{$op_sums = [
	'BONUS'=>$_TRANS['Amount'],
	'PENALTY'=>$_TRANS['Amount'],
	'CASHIN'=>$_TRANS['Amount to add'],
	'CASHOUT'=>$_TRANS['Amount to withdraw'],
	'EX'=>$_TRANS['Amount to exchange'],
	'TR'=>$_TRANS['Amount to receive'],
	'TRIN'=>$_TRANS['Received amount'],
	'BUY'=>$_TRANS['Amount'],
	'SELL'=>$_TRANS['Amount'],
	'BUY2'=>$_TRANS['Amount'],
	'SELL2'=>$_TRANS['Amount'],
	'REF'=>$_TRANS['Amount'],
	'GIVE'=>$_TRANS['Deposit amount'],
	'TAKE'=>$_TRANS['Amount to receive'],
	'CALCIN'=>$_TRANS['Amount'],
	'CALCOUT'=>$_TRANS['Amount']
] scope='global'}
{$aop_names = [
	'BONUS'=>$_TRANS['Bonus'],
	'PENALTY'=>$_TRANS['Penalty'],
	'CASHIN'=>$_TRANS['Add funds'],
	'CASHOUT'=>$_TRANS['Withdraw'],
	'EX'=>$_TRANS['Exchange'],
	'TR'=>$_TRANS['Transfer']
] scope='global'}
