{$_tstates = [
1 => $_TRANS['new'],
2 => $_TRANS['Awaiting Reply'],
3 => $_TRANS['In progress'],
4 => $_TRANS['Processed'],
5 => $_TRANS['Reply sent'],
8 => $_TRANS['Detained'],
9 => $_TRANS['Closed']
] scope='global'}